### ISSUE TITLE
About Lastline data。。

### ISSUE THREAD

**Issue by Everyday-seu** [Thijsvanede/DeepCASE#1]
Thanks for sharing your great job!!!But how can I get the Lastline data?Hope for your response :p

**Comment by Thijsvanede** [comment]
Thank you for your interest in DeepCASE, I appreciate it!
Unfortunately, due to the NDA we signed, we cannot share the Lastline dataset with anyone ([see here](https://github.com/Thijsvanede/DeepCASE/tree/main/data#Lastline-dataset)).
Real-world security alert data may contain sensitive data from customers and therefore this data cannot be shared.

If you would like to use DeepCASE, it should offer support for any of your own data (see [deepcase.readthedocs.io](https://deepcase.readthedocs.io/en/latest/usage/usage.html), and can be tested with the HDFS dataset that is openly available for download [here](https://github.com/wuyifan18/DeepLog/tree/master/data).

Good luck with your future efforts!
